feat: Add Page Metadatas with I18N - MEED-2081
Meeds-io/deeds-dapp pull request #475
Opened 2023-05-05 11:58 UTC by MayTekayaa

2023-05-10 14:21 UTC, boubaker approved these changes, later dismissed

2023-05-10 14:35 UTC, plamarque commented on deeds-dapp-webapp/src/main/webapp/WEB-INF/metadata/about-us.html
> +<link rel="alternate" href="https://www.meeds.io/qui-somme-nous?lang=fr" hreflang="fr"/>
there is a typo here. it should be qui-sommes-nous

2023-05-10 14:35 UTC, plamarque commented on deeds-dapp-webapp/src/main/webapp/WEB-INF/metadata/legals.html
> +<link rel="alternate" href="https://www.meeds.io/legales?lang=fr" hreflang="fr"/>
should rather be /mentions-legales

2023-05-10 14:50 UTC, boubaker approved these changes

2023-05-10 15:04 UTC, exo-swf commented
Your PR triggers too many exo-ci builds! Please finish your work and then, set your PR ready! Thank you

2023-05-11 07:02 UTC, plamarque commented on deeds-dapp-webapp/src/main/webapp/static/i18n/messages_fr.properties
> +metadata.tokenomics.pageTitle=Ɱeeds Tokenomics -Jeton Ɱeed | Meeds DAO
```suggestion
metadata.tokenomics.pageTitle=Ɱeeds Tokenomics - Jeton Ɱeed | Meeds DAO
```

2023-05-11 07:03 UTC, plamarque commented on deeds-dapp-webapp/src/main/webapp/static/i18n/messages_fr.properties
> +metadata.tokenomics.imageAlt=Ɱeeds Tokenomics -Jeton Ɱeed | Meeds DAO
```suggestion
metadata.tokenomics.imageAlt=Ɱeeds Tokenomics - Jeton Ɱeed | Meeds DAO
```

2023-05-11 07:03 UTC, plamarque requested changes, later dismissed
small typos

2023-05-11 10:59 UTC, boubaker commented on deeds-dapp-service/src/test/java/io/meeds/deeds/web/filter/RequestDispatcherFilterTest.java
> +    dispatcherFilter.doFilter(request, response, chain);
there is not test after making the operation, please add assertions to make the test relevant

2023-05-11 15:05 UTC, merged